### ISSUE TITLE
not working with sl3000?

### ISSUE THREAD

**Issue by MH32123** [ready-dl/pyplayready#10]
i got sl3k files but i have this error:
INFO:root:pyplayready version 0.3.5 Copyright (c) 2024-2024 DevLARLEY, Erevoc, DevataDev
INFO:root:https://github.com/ready-dl/pyplayready
INFO:root:Run 'pyplayready --help' for help

  File "C:\Users\Administrator\Downloads\DRM\pyplayready-main\pyplayready\main.py", line 150, in create_device
    group_key = ECCKey.load(group_key)
  File "C:\Users\Administrator\Downloads\DRM\pyplayready-main\pyplayready\ecc_key.py", line 76, in load
    return cls.loads(f.read())
  File "C:\Users\Administrator\Downloads\DRM\pyplayready-main\pyplayready\ecc_key.py", line 63, in loads
    raise ValueError(f"Invalid data length. Expecting 96 or 32 bytes, got {len(data)}")
ValueError: Invalid data length. Expecting 96 or 32 bytes, got 21

**Comment by DevLARLEY** [comment]
21 bytes? what's the file called you're trying to load?

**Comment by MH32123** [comment]
> 21 bytes? what's the file called you're trying to load?

it's zgpriv.dat, the person who gave it to me claimed it's for sl3000

**Comment by DevLARLEY** [comment]
It's not possible that this is actually a valid group key. As the error said, it must either be 32 or 96 bytes in length

**Comment by DRM-Lab** [comment]
Just someone scam you that it’s not SL3000

**Comment by kotuk** [comment]
I haven't seen anyone who sells SL3k

**Comment by DRM-Lab** [comment]
Normal and not will see

**Comment by MH32123** [comment]
> Just someone scam you that it’s not SL3000
No scam lol
I didn't buy it

**Comment by chu23465** [comment]
I actually extracted files from this rom 
https://samfw.com/firmware/GT-N7108/CHM/N7108ZMUEOI3
https://samfw.com/firmware/GT-N7102/CHN/N7102ZCUEOJ1
The group key was also 21 bytes long. Same with other ROM.

**Comment by chu23465** [comment]
[bgroupcert.txt](https://github.com/user-attachments/files/17920411/bgroupcert.txt)
[priv.txt](https://github.com/user-attachments/files/17920415/priv.txt)
[zgpriv.txt](https://github.com/user-attachments/files/17920417/zgpriv.txt)
(Renamed from .dat to .txt do that github uploads it)

**Comment by marioeivissa** [comment]
> I actually extracted files from this rom https://samfw.com/firmware/GT-N7108/CHM/N7108ZMUEOI3 https://samfw.com/firmware/GT-N7102/CHN/N7102ZCUEOJ1 The group key was also 21 bytes long. Same with other ROM.
> 
> Just to be sure I extracted the certs multiple times to make sure I didn't make a mistake with decompression or something. All times the cert was 21 bytes long.

how do you extrack sl3k from a rom?????if sl3k is from hardware mate

**Comment by izof87** [comment]
SL3K mean interact with hardware layer arm TEE.

**Comment by marioeivissa** [comment]
> SL3K significa interactuar con el brazo de capa de hardware TEE.

do you know get sl3k????contac with me by tg if you want

**Comment by 3052** [comment]
I extracted this myself:

 https://samfw.com/firmware/GT-N7108/CHM/N7108ZMUEOI3

I see this in devCertTemplate.dat

~~~xml
<SECURITYLEVEL>2000</SECURITYLEVEL>
~~~

so the obvious question is, assuming the device is actually valid, what makes you think its SL3000?

**Comment by chu23465** [comment]
To clarify I don't think the cert I posted is SL3K.

**Comment by izof87** [comment]
> > SL3K significa interactuar con el brazo de capa de hardware TEE.
> 
> do you know get sl3k????contac with me by tg if you want

from TV's android or vidaa  ,yes can dump key and certificat SL3K.

**Comment by izof87** [comment]
ya ,  zgpriv_protected.dat decoded (SRAM) only in secure area like arm cortex series  TEE  (A9 or A55 exampl l), as mentioned from oficial arm™ Dev  

>>

https://developer.arm.com/documentation/PRD29-GENC-009492/c/TrustZone-Hardware-Architecture

**Comment by Kyladon** [comment]
> ya , zgpriv_protected.dat decoded (SRAM) only in secure area like arm cortex series TEE (A9 or A55 exampl l), as mentioned from oficial arm™ Dev
> 

Where are these files located in the TEE file structure? I've been trying to locate them from my dump of it but struggling to find them. WV is all sorted from the dump, just not PR.

**Comment by 3052** [comment]
here is an example of the infamous 21 byte:

https://dumps.tadiphone.dev/dumps/KDDI/scv31/-/tree/zeroltekdi-user-7.0-NRD90M-SCV31KDU1CQG1-release-keys/system/etc/security/.drm

as expected most or all of the files are malformed - for example `devcerttemplate.dat`

**Comment by 3052** [comment]
> Expecting 96 or 32 bytes, got 21

OK we found out that if you convert the code page to one of these
ISO 8859-1
ISO 8859-9
you get 32 bytes - however even with that it seems to not be a valid key - so not sure

**Comment by marioeivissa** [comment]
> ya , zgpriv_protected.dat decoded (SRAM) only in secure area like arm cortex series TEE (A9 or A55 exampl l), as mentioned from oficial arm™ Dev
> 
> > >
> 
> https://developer.arm.com/documentation/PRD29-GENC-009492/c/TrustZone-Hardware-Architecture

i have vidaa hisense tv, so contact with me if you want by tg, same nick

**Comment by marioeivissa** [comment]
> It's not possible that this is actually a valid group key. As the error said, it must either be 32 or 96 bytes in length

so mate will you make extension playreadyproxy?????
