### ISSUE TITLE
get_license_challenge argument

### ISSUE THREAD

**Issue by 3052** [ready-dl/pyplayready#7]
I see this:

https://github.com/ready-dl/pyplayready/blob/34056f046a646e48d44bc5fcd4e7ad35b369e088/pyplayready/cdm.py#L173

but it seems actually that WRMHEADER is provided

https://github.com/ready-dl/pyplayready/blob/34056f046a646e48d44bc5fcd4e7ad35b369e088/pyplayready/main.py#L58

so should the function signature be corrected?

**Comment by DevLARLEY** [comment]
Fixed as of https://github.com/ready-dl/pyplayready/commit/34056f046a646e48d44bc5fcd4e7ad35b369e088
